### ISSUE TITLE
Possible improvement for startup version check

### ISSUE THREAD

**Issue by ToniHeiss** [sibvisions/flutter_jvx#181]
When the startup endpoint is not yet know to the server (e.g. "v5/startup"), the client/server version-check is not done. Therefore, the nice "incompatible versions"-exception message is not shown, instead an exception is thrown with "Server doesn't support '/v5/startup'." We should check if this is intended behaviour or if we should have an independant version check apart from the startup itself.

**Comment by rjahn** [comment]
The version check on server-side works with every startup endpoint not just v5. If you use e.g. /mystartup as endpoint, it also won't work because the server doesn't know the endpoint.

So in your use-case, you have a newer client and are trying to connect to an older server, right?
Sure, this is a problem.

In this case, we should show a different message, because the server is too old... but we don't know the server version.

If startup fails with 404, it's possible that the server is available but the app name is wrong...
So it's hard to find the root cause of the problem.

The client side version check is not the solution!

**Comment by ToniHeiss** [comment]
>So in your use-case, you have a newer client and are trying to connect to an older server, right?
>If startup fails with 404, it's possible that the server is available but the app name is wrong...

Yes, correct. That was the problem. Because we always show this message "Server does not support /v5/startup" on 404, we can't be sure if this is the problem, but we show this as beeing the problem. 

Not that big of a problem, just wanted to document this behaviour as it has happened to me.

**Comment by rjahn** [comment]
From my point of view, everything is fine and the message has enough details. The version check is more or less important for the client-side and the server-side should be up-to-date.... It's easy to update the server-side but it's not so easy to update the mobile clients.

I'm always open for improvements but in this special case, I have no idea what's better.
