### ISSUE TITLE
Lock language setting while in offline

### ISSUE THREAD

**Issue by ToniHeiss** [sibvisions/flutter_jvx#183]
Changing the language while in offline mode already has no effect, but it is still selectable and registers as a change, therefore user see the newly selected language as set and can press "save" at the end of it. Only upon returning to the settings page will they notice that their change had no effect and is the language is set back to the initial value. 

It seems rather unintuitive to leave a setting as changeable and then not enforce the change of a setting, instead of just locking the setting outright. I propose the locking of the language settings while in offline mode outright to decrease confusion.

**Comment by rjahn** [comment]
It shouldn't be a problem to change the language because translation is already in cache? So it should work without any problems?.

In general: Yes, if a value change doesn't really change something -> disable or hide the option. Disabling is better for UX.

**Comment by ToniHeiss** [comment]
If we already have the language files then we could also allow the user to change the language to all the languages where translation files have been downloaded and are currently present in the app while offline. 

Either way is fine. Locking or just allowing pre-downloaded selection.

**Comment by rjahn** [comment]
If we "go offline", the app was started and everything is in cache... because the online mode also need the files. If we are offline, we have everything in place. Sure, if you create offline screens the translation should be recognized/used.

I guess the translation change in offline mode is a bug.

**Comment by Bungeefan** [comment]
The settings dropdown shows all currently supported languages, which are defined by looking at the local translation files (Keyword: AppOverview) and the already downloaded translation files from the server.
Changing the language to a selectable entry should therefore theoretically work fine while being offline.

**But currently, it doesn't work for two reasons.**

In greater explanation, we have a user language and an application language, the user language is defined by the user and only by the user and the application language (which has a higher priority) is defined by the server, which in turn can return the same as the preferred user language, effectively respecting the user's choice.

Now the user goes offline and wants to change the language, which would usually update the application language after the restart, but there is no restart.
First problem is that the save button, just doesn't do anything when offline, just routing back (Easy fix).
The second problem is the still saved application language, which is now old and doesn't reflect the user preference anymore, but still overwrites the user preference.

* We would either need to clear the application language manually when going offline, which could result in confusing UX.
  * For example, the server forces EN, but the user has DE as preference selected. After changing to offline, the app which was up to now forced to English is now in German. And vice versa when going online.
* Or the server would stop sending a application language as long as it isn't forced, and we would locally handle the user language. The server would still have our selected language as we send it in the startup.


**Additionally**, we should probably show forced server settings somewhere in the UI, as currently the user has no chance to effectively understand why his (in this case language) switch doesn't work (even without the bug mentioned above).

**Comment by mhandsteiner** [comment]
Offline language detection would be consistant, when MobileLauncher sets an additional application parameter, in case the language is configured fix in application.xml. (eg: Application.language.isfixed = true or alternative a Application.language.configured = value of Application.language). This can be easily set in updateConfiguration, if (!StringUtil.isEmpty(getParameter(ILauncher.PARAM_APPLICATIONLANGUAGE))).
Then in Offline Mode the language detection is: 
  Application.language.isfixed == true: app-language 
  Application.language.isfixed == false: user-language or system-language, if user.language is not set.
  
app-language means, the language that the server sent in Language response.
user-language means, the language that the user has choosen in settings.
system-language means, the language of the device.

**Comment by rjahn** [comment]
I'm not sure if we talk about the same things.

App translation is the translation which is included in native app. Used for translation of text which is shown before the startup of an application (app overview).

User translation is the translation received from the server-side application.


Use the app translation for every text and message will be shown before the startup of an application. And use the user-language if an application is started. So simply: user-translation -> fall-back to app translation to support translation of texts which are not defined in user translation.

Which language: System language (default) -> if user sets a different language via application settings -> store this language and just use it. So you know if user has set the language on mobile device.

If no custom language is set -> Use system language... BUT the server sends you the language - and here's a problem?

It's possible that the System language is German and the app overview is German and an application is in English because it's configured in English.

I guess your problem is that the language sent from server is the default language of server. If server runs English, the default language is English but should be German?
So the application should send: Client - use-your-default-language?


BUT this issue was about offline mode. In offline mode it should be possible to change the language without any problems!

**Comment by rjahn** [comment]
response will contain the property: customLanguage

If available and set -> hide or disable language in settings

if this property is set, it means that the language is fixed.

**Comment by Bungeefan** [comment]
**Note:** This is a breaking change for old servers, as we now only respect the server language if `customLanguage` is set.

Should we increment the server version?

**Comment by rjahn** [comment]
Why?

The only difference should be tat the client locks the language!

The rest should work like before!
